# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - all

linters:
  enable:
    - errcheck
    - goimports
    - golint
    - govet
    - staticcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Shutdown|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "exported (type|method|function|const|var) (.+) should have comment(.+)or be unexported"
