{
 "title": "Fuddle",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count By Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(fuddle_cluster_nodes_count{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Up Members By Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(fuddle_registry_members_count{status=\"up\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Down Members By Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(fuddle_registry_members_count{status=\"down\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Left Members By Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 19 },
   "targets": [
    {
     "expr": "sum(fuddle_registry_members_count{status=\"left\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members By Owner",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
   "targets": [
    {
     "expr": "sum(fuddle_registry_members_owned{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Registry Client Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Inbound Client Updates / Second By Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(fuddle_registry_updates_client_inbound{}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Client Updates / Second By Update Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(fuddle_registry_updates_client_inbound{}[$__rate_interval])) by (updatetype)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Client Updates / Second By Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(fuddle_registry_updates_client_outbound{}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Registry Replica Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Successful Outbound Replica Updates / Second By Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(fuddle_registry_replica_updates_outbound{status=\"ok\"}[$__rate_interval])) by (target)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Outbound Replica Updates / Second By Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(fuddle_registry_replica_updates_outbound{status=\"fail\"}[$__rate_interval])) by (target)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Replica Updates / Second By Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(fuddle_registry_replica_updates_inbound{}[$__rate_interval])) by (source)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Replica Repair", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Successful Inbound Repair Updates / Second By Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(fuddle_registry_repair_updates_inbound{status=\"ok\"}[$__rate_interval])) by (source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Inbound Repair Updates / Second By Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(fuddle_registry_repair_updates_inbound{status=\"fail\"}[$__rate_interval])) by (source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Repair Updates / Second By Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(fuddle_registry_repair_updates_outbound{}[$__rate_interval])) by (target)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error / Second By Subsystem",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(rate(fuddle_errors{}[$__rate_interval])) by (subsystem) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Warnings / Second By Subsystem",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum(rate(fuddle_warnings{}[$__rate_interval])) by (subsystem) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error / Second By Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(rate(fuddle_errors{}[$__rate_interval])) by (instance) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Warnings / Second By Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "sum(rate(fuddle_warnings{}[$__rate_interval])) by (instance) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}