// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CounterClient is the client API for Counter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CounterClient interface {
	// Stream sends and receives updates containing the count for different IDs.
	//
	// Clients will send the local count to the server, which is the number of
	// users registered with the ID on the client node. Then the server
	// aggregates the counts and broadcasts the global count to each client.
	Stream(ctx context.Context, opts ...grpc.CallOption) (Counter_StreamClient, error)
}

type counterClient struct {
	cc grpc.ClientConnInterface
}

func NewCounterClient(cc grpc.ClientConnInterface) CounterClient {
	return &counterClient{cc}
}

func (c *counterClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Counter_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Counter_ServiceDesc.Streams[0], "/Counter/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &counterStreamClient{stream}
	return x, nil
}

type Counter_StreamClient interface {
	Send(*CountUpdate) error
	Recv() (*CountUpdate, error)
	grpc.ClientStream
}

type counterStreamClient struct {
	grpc.ClientStream
}

func (x *counterStreamClient) Send(m *CountUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *counterStreamClient) Recv() (*CountUpdate, error) {
	m := new(CountUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CounterServer is the server API for Counter service.
// All implementations must embed UnimplementedCounterServer
// for forward compatibility
type CounterServer interface {
	// Stream sends and receives updates containing the count for different IDs.
	//
	// Clients will send the local count to the server, which is the number of
	// users registered with the ID on the client node. Then the server
	// aggregates the counts and broadcasts the global count to each client.
	Stream(Counter_StreamServer) error
	mustEmbedUnimplementedCounterServer()
}

// UnimplementedCounterServer must be embedded to have forward compatible implementations.
type UnimplementedCounterServer struct {
}

func (UnimplementedCounterServer) Stream(Counter_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedCounterServer) mustEmbedUnimplementedCounterServer() {}

// UnsafeCounterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CounterServer will
// result in compilation errors.
type UnsafeCounterServer interface {
	mustEmbedUnimplementedCounterServer()
}

func RegisterCounterServer(s grpc.ServiceRegistrar, srv CounterServer) {
	s.RegisterService(&Counter_ServiceDesc, srv)
}

func _Counter_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CounterServer).Stream(&counterStreamServer{stream})
}

type Counter_StreamServer interface {
	Send(*CountUpdate) error
	Recv() (*CountUpdate, error)
	grpc.ServerStream
}

type counterStreamServer struct {
	grpc.ServerStream
}

func (x *counterStreamServer) Send(m *CountUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func (x *counterStreamServer) Recv() (*CountUpdate, error) {
	m := new(CountUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Counter_ServiceDesc is the grpc.ServiceDesc for Counter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Counter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Counter",
	HandlerType: (*CounterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Counter_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "counter.proto",
}
