version: '3'

services:
  fcm:
    image: fuddle:latest
    container_name: fcm
    command: fuddle fcm start --bind-addr 0.0.0.0 --cluster --cluster-log-dir /fcm/logs
    ports:
      - "8220:8220"
    expose:
      - "1-65536"
    networks:
      - fcm
    build:
      context: ../..
      dockerfile: ./dev/Dockerfile
    volumes:
      - ./logs:/fcm/logs

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - fcm
    depends_on:
      - fcm

  grafana:
    image: grafana/grafana:8.5.22
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - fcm
    depends_on:
      - prometheus

networks:
  fcm:
    driver: bridge
