global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'fuddle'
    metrics_path: '/metrics'
    scheme: 'http'

    http_sd_configs:
      - url: 'http://fcm:8220/cluster/default/prometheus/targets'
        refresh_interval: 10s
