// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package clock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClockClient is the client API for Clock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClockClient interface {
	Time(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error)
}

type clockClient struct {
	cc grpc.ClientConnInterface
}

func NewClockClient(cc grpc.ClientConnInterface) ClockClient {
	return &clockClient{cc}
}

func (c *clockClient) Time(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error) {
	out := new(TimeResponse)
	err := c.cc.Invoke(ctx, "/clock.Clock/Time", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClockServer is the server API for Clock service.
// All implementations must embed UnimplementedClockServer
// for forward compatibility
type ClockServer interface {
	Time(context.Context, *TimeRequest) (*TimeResponse, error)
	mustEmbedUnimplementedClockServer()
}

// UnimplementedClockServer must be embedded to have forward compatible implementations.
type UnimplementedClockServer struct {
}

func (UnimplementedClockServer) Time(context.Context, *TimeRequest) (*TimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Time not implemented")
}
func (UnimplementedClockServer) mustEmbedUnimplementedClockServer() {}

// UnsafeClockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClockServer will
// result in compilation errors.
type UnsafeClockServer interface {
	mustEmbedUnimplementedClockServer()
}

func RegisterClockServer(s grpc.ServiceRegistrar, srv ClockServer) {
	s.RegisterService(&Clock_ServiceDesc, srv)
}

func _Clock_Time_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClockServer).Time(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clock.Clock/Time",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClockServer).Time(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Clock_ServiceDesc is the grpc.ServiceDesc for Clock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clock.Clock",
	HandlerType: (*ClockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Time",
			Handler:    _Clock_Time_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
