name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Protoc
        run: PROTOC_ZIP=protoc-22.2-linux-x86_64.zip &&
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v22.2/$PROTOC_ZIP &&
          unzip -o $PROTOC_ZIP -d /usr/local bin/protoc &&
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 &&
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Generate
        run: go generate ./...

      - name: Build
        run: go build ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Protoc
        run: PROTOC_ZIP=protoc-22.2-linux-x86_64.zip &&
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v22.2/$PROTOC_ZIP &&
          unzip -o $PROTOC_ZIP -d /usr/local bin/protoc &&
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 &&
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Generate
        run: go generate ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Protoc
        run: PROTOC_ZIP=protoc-22.2-linux-x86_64.zip &&
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v22.2/$PROTOC_ZIP &&
          unzip -o $PROTOC_ZIP -d /usr/local bin/protoc &&
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 &&
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Generate
        run: go generate ./...

      - name: Unit Tests
        run: go test ./... -timeout=30s

      - name: Integration Tests
        run: go test ./... -tags=integration -timeout=30s
